import { useState } from 'react';
import { Alert, Box, Button, Card, CardContent, Checkbox, FormControlLabel, IconButton, InputAdornment, Link as MuiLink, Stack, TextField, Typography } from '@mui/material';
import VisibilityRoundedIcon from '@mui/icons-material/VisibilityRounded';
import VisibilityOffRoundedIcon from '@mui/icons-material/VisibilityOffRounded';
import ArrowBackRoundedIcon from '@mui/icons-material/ArrowBackRounded';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { useAuth } from '../../contexts/AuthContext';
import { useTranslation } from '../../contexts/LanguageContext';
import { isSupabaseConfigured } from '../../lib/supabase';
import { requestPasswordReset } from '../../services/authService';

export default function LoginPage() { const { t } = useTranslation(); const { signIn, previewSignIn } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [show, setShow] = useState(false); const [remember, setRemember] = useState(true); const [mode, setMode] = useState('login'); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false); const from = location.state?.from || '/admin';
  const submit = async (event) => { event.preventDefault(); setError(''); setNotice(''); if (!email || (mode === 'login' && !password)) { setError('Enter the required fields.'); return; } setLoading(true); try { if (mode === 'reset') { await requestPasswordReset(email); setNotice(t('auth.emailSent')); } else { await signIn(email, password); navigate(from); } } catch (err) { setError(err.message || 'Unable to sign in.'); } finally { setLoading(false); } };
  const preview = () => { previewSignIn(); navigate('/admin'); };
  return <Box className="auth-shell"><Box className="auth-visual"><Link to="/" className="brand footer-brand"><span className="brand-mark">✳</span><span><b>Agri</b> Pulse<small>KNOWLEDGE FOR THE FIELD</small></span></Link><Box className="auth-visual-copy"><Typography className="eyebrow">AGRI PULSE / ADMIN</Typography><Typography variant="h2">A calmer way to move good knowledge into the world.</Typography><Typography color="rgba(255,255,255,.65)" sx={{ mt: 2 }}>Manage bilingual stories, field videos, and useful references from one focused workspace.</Typography></Box></Box><Box className="auth-panel"><Link to="/" className="back-link"><ArrowBackRoundedIcon fontSize="small" /> {t('auth.backToSite')}</Link><Card className="auth-card"><CardContent sx={{ p: { xs: 2.5, sm: 4 } }}><Typography className="eyebrow">SECURE WORKSPACE</Typography><Typography variant="h3" sx={{ mt: 1 }}>{mode === 'reset' ? 'Reset your password' : t('auth.welcome')}</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>{mode === 'reset' ? 'Enter your account email and we will request a secure reset link.' : t('auth.subtitle')}</Typography>{!isSupabaseConfigured && <Alert severity="info" variant="outlined" sx={{ mt: 3 }}>{t('auth.setupText')}</Alert>}{error && <Alert severity="error" sx={{ mt: 2 }}>{error}</Alert>}{notice && <Alert severity="success" sx={{ mt: 2 }}>{notice}</Alert>}<Box component="form" onSubmit={submit} sx={{ mt: 3 }}><Stack gap={2}><TextField label={t('auth.email')} type="email" required value={email} onChange={(event) => setEmail(event.target.value)} autoComplete="email" />{mode === 'login' && <TextField label={t('auth.password')} required type={show ? 'text' : 'password'} value={password} onChange={(event) => setPassword(event.target.value)} autoComplete="current-password" InputProps={{ endAdornment: <InputAdornment position="end"><IconButton onClick={() => setShow((value) => !value)} aria-label="Show password">{show ? <VisibilityOffRoundedIcon /> : <VisibilityRoundedIcon />}</IconButton></InputAdornment> }} />}</Stack>{mode === 'login' && <Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mt: 1 }}><FormControlLabel control={<Checkbox checked={remember} onChange={(event) => setRemember(event.target.checked)} size="small" />} label="Remember me" /><Button type="button" size="small" onClick={() => { setMode('reset'); setError(''); }}>{t('auth.forgot')}</Button></Stack>}<Button type="submit" variant="contained" fullWidth size="large" disabled={loading} sx={{ mt: 2 }}>{mode === 'reset' ? t('auth.reset') : t('auth.signIn')}</Button></Box>{!isSupabaseConfigured && mode === 'login' && <><Box className="auth-divider"><span>or</span></Box><Button onClick={preview} variant="outlined" fullWidth size="large">{t('auth.preview')}</Button></>}{mode === 'reset' && <Button fullWidth sx={{ mt: 1 }} onClick={() => setMode('login')}>{t('common.back')}</Button>}</CardContent></Card></Box></Box>; }
