import { useEffect, useState } from 'react';
import { Box, Button, Chip, Container, Grid, InputAdornment, Stack, TextField, Typography } from '@mui/material';
import ArrowForwardRoundedIcon from '@mui/icons-material/ArrowForwardRounded';
import MailOutlineRoundedIcon from '@mui/icons-material/MailOutlineRounded';
import { Link } from 'react-router-dom';
import { useLanguage, useTranslation } from '../../contexts/LanguageContext';
import { listContent } from '../../services/contentService';
import { news as sampleNews, videos as sampleVideos, resources as sampleResources, categories, stats } from '../../data/contentData';
import NewsCard from '../../components/news/NewsCard';
import VideoCard from '../../components/videos/VideoCard';
import ResourceCard from '../../components/resources/ResourceCard';
import SectionHeading from '../../components/common/SectionHeading';

export default function HomePage() {
  const { t } = useTranslation(); const { language } = useLanguage(); const [content, setContent] = useState({ news: sampleNews.filter((item) => item.status === 'published'), videos: sampleVideos, resources: sampleResources });
  useEffect(() => { Promise.all([listContent('news'), listContent('videos'), listContent('resources')]).then(([newsData, videoData, resourceData]) => setContent({ news: newsData, videos: videoData, resources: resourceData })).catch(() => {}); }, []);
  return <>
    <section className="hero-section"><Container maxWidth="lg"><Grid container spacing={5} alignItems="center"><Grid size={{ xs: 12, md: 7 }}><Chip label={t('home.heroTag')} className="hero-chip" /><Typography variant="h1" className="hero-title">{t('home.title')}</Typography><Typography className="hero-subtitle">{t('home.subtitle')}</Typography><Stack direction={{ xs: 'column', sm: 'row' }} gap={1.5} sx={{ mt: 4 }}><Button component={Link} to="/news" variant="contained" size="large" endIcon={<ArrowForwardRoundedIcon />}>{t('home.browse')}</Button><Button component={Link} to="/resources" variant="outlined" size="large">{t('home.learn')}</Button></Stack><Stack direction="row" gap={{ xs: 2, sm: 4 }} sx={{ mt: 6 }}>{stats.map((stat) => <Box key={stat.value}><Typography variant="h4" sx={{ fontWeight: 800 }}>{stat.value}</Typography><Typography variant="caption" color="text.secondary">{stat[`label_${language}`]}</Typography></Box>)}</Stack></Grid><Grid size={{ xs: 12, md: 5 }}><Box className="hero-art"><Box className="hero-image" /><Box className="hero-note"><Typography variant="overline">FIELD NOTE 01</Typography><Typography variant="h6">“Observe first. Decide with context.”</Typography><Typography variant="caption">A simple habit for every growing season.</Typography></Box><span className="sun-disc" /><span className="leaf leaf-one" /><span className="leaf leaf-two" /></Box></Grid></Grid></Container></section>
    <section className="section"><Container maxWidth="lg"><SectionHeading eyebrow="01 / STORIES" title={t('home.latest')} subtitle={t('home.latestSub')} link="/news" linkLabel={t('common.viewAll')} /><Grid container spacing={2.5}>{content.news.slice(0, 3).map((item) => <Grid key={item.id} size={{ xs: 12, md: 4 }}><NewsCard item={item} /></Grid>)}</Grid></Container></section>
    <section className="section muted-section"><Container maxWidth="lg"><SectionHeading eyebrow="02 / LEARNING" title={t('home.videos')} subtitle={t('home.videosSub')} link="/videos" linkLabel={t('common.viewAll')} /><Grid container spacing={2.5}>{content.videos.slice(0, 3).map((item) => <Grid key={item.id} size={{ xs: 12, sm: 6, md: 4 }}><VideoCard item={item} /></Grid>)}</Grid></Container></section>
    <section className="section"><Container maxWidth="lg"><SectionHeading eyebrow="03 / EXPLORE" title={t('home.categories')} subtitle={t('home.categoriesSub')} /><Grid container spacing={1.5}>{categories.map((category) => <Grid key={category.id} size={{ xs: 6, sm: 4, md: 2 }}><Link to={`/news?category=${category.id}`} className="category-tile" style={{ background: category.color }}><span>{category.icon}</span><Typography variant="subtitle2">{category[`name_${language}`]}</Typography><ArrowForwardRoundedIcon fontSize="small" /></Link></Grid>)}</Grid></Container></section>
    <section className="section resource-section"><Container maxWidth="lg"><SectionHeading eyebrow="04 / KEEP CLOSE" title={t('home.resources')} subtitle={t('home.resourcesSub')} link="/resources" linkLabel={t('common.explore')} /><Grid container spacing={2.5}>{content.resources.map((item) => <Grid key={item.id} size={{ xs: 12, md: 4 }}><ResourceCard item={item} /></Grid>)}</Grid></Container></section>
    <section className="newsletter-section"><Container maxWidth="md"><Stack alignItems="center" textAlign="center"><Typography className="eyebrow">FIELD NOTES, OCCASIONALLY</Typography><Typography variant="h3" sx={{ mt: 1 }}>{t('home.newsletter')}</Typography><Typography color="text.secondary" sx={{ mt: 1, maxWidth: 520 }}>{t('home.newsletterSub')}</Typography><TextField placeholder={t('home.email')} sx={{ mt: 3, width: 'min(100%, 440px)' }} InputProps={{ endAdornment: <InputAdornment position="end"><Button variant="contained" endIcon={<MailOutlineRoundedIcon />}>{t('home.subscribe')}</Button></InputAdornment> }} /></Stack></Container></section>
  </>;
}
