import { useEffect, useState } from 'react';
import { Box, Button, Card, CardContent, Grid, Stack, Typography } from '@mui/material';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import ArrowForwardRoundedIcon from '@mui/icons-material/ArrowForwardRounded';
import PendingActionsRoundedIcon from '@mui/icons-material/PendingActionsRounded';
import PublishedWithChangesRoundedIcon from '@mui/icons-material/PublishedWithChangesRounded';
import EditNoteRoundedIcon from '@mui/icons-material/EditNoteRounded';
import GroupRoundedIcon from '@mui/icons-material/GroupRounded';
import { Link } from 'react-router-dom';
import { useTranslation } from '../../contexts/LanguageContext';
import { listDashboardContent } from '../../services/contentService';
import { formatDate, localized } from '../../utils/formatters';
import { useLanguage } from '../../contexts/LanguageContext';
import StatusChip from '../../components/common/StatusChip';

export default function AdminDashboard() { const { t } = useTranslation(); const { language } = useLanguage(); const [data, setData] = useState({ pending: 2, published: 24, drafts: 4, all: [] }); useEffect(() => { listDashboardContent().then(setData).catch(() => {}); }, []); const statItems = [[t('admin.pending'), data.pending, PendingActionsRoundedIcon, 'warning'], [t('admin.published'), data.published, PublishedWithChangesRoundedIcon, 'success'], [t('admin.drafts'), data.drafts, EditNoteRoundedIcon, 'default'], [t('admin.contributors'), '06', GroupRoundedIcon, 'primary']]; return <><Stack direction={{ xs: 'column', sm: 'row' }} justifyContent="space-between" gap={2} sx={{ mb: 4 }}><Box><Typography className="eyebrow">ADMIN / OVERVIEW</Typography><Typography variant="h3" sx={{ mt: 1 }}>{t('admin.dashboard')}</Typography><Typography color="text.secondary" sx={{ mt: 1 }}>{t('admin.overview')}</Typography></Box><Button component={Link} to="/admin/news/new" variant="contained" startIcon={<AddRoundedIcon />}>{t('admin.newStory')}</Button></Stack><Grid container spacing={2} sx={{ mb: 4 }}>{statItems.map(([label, value, Icon, color]) => <Grid key={label} size={{ xs: 6, md: 3 }}><Card className="stat-card"><CardContent><Stack direction="row" justifyContent="space-between" alignItems="flex-start"><Typography variant="body2" color="text.secondary">{label}</Typography><Icon color={color} /></Stack><Typography variant="h3" sx={{ mt: 2 }}>{value}</Typography></CardContent></Card></Grid>)}</Grid><Grid container spacing={2.5}><Grid size={{ xs: 12, md: 7 }}><Card><CardContent sx={{ p: 3 }}><Stack direction="row" justifyContent="space-between" alignItems="center" sx={{ mb: 2.5 }}><Typography variant="h6">{t('admin.review')}</Typography><Button component={Link} to="/admin/news" endIcon={<ArrowForwardRoundedIcon />}>{t('admin.manage')}</Button></Stack><Stack divider={<Box component="span" sx={{ borderBottom: '1px solid', borderColor: 'divider' }} />}>
    {(data.all.filter((item) => item.status !== 'published').slice(0, 4).length ? data.all.filter((item) => item.status !== 'published').slice(0, 4) : [{ id: 'empty', title_en: 'No pending items', title_ta: 'மதிப்பாய்வில் உள்ளவை இல்லை', status: 'published' }]).map((item) => <Stack key={item.id} direction="row" alignItems="center" justifyContent="space-between" sx={{ py: 1.7 }}><Box><Typography fontWeight={700}>{localized(item, 'title', language)}</Typography><Typography variant="caption" color="text.secondary">{item.date ? formatDate(item.date, language) : '—'}</Typography></Box><StatusChip status={item.status} /></Stack>)}
  </Stack></CardContent></Card></Grid><Grid size={{ xs: 12, md: 5 }}><Card className="admin-quick-card"><CardContent sx={{ p: 3 }}><Typography variant="h6">Quick actions</Typography><Typography color="rgba(255,255,255,.72)" sx={{ mt: 1 }}>Keep the library moving with a few focused actions.</Typography><Stack gap={1.2} sx={{ mt: 3 }}><Button component={Link} to="/admin/videos/new" variant="contained" color="secondary" startIcon={<AddRoundedIcon />} fullWidth>{t('admin.newVideo')}</Button><Button component={Link} to="/admin/resources/new" variant="outlined" sx={{ color: 'white', borderColor: 'rgba(255,255,255,.35)' }} startIcon={<AddRoundedIcon />} fullWidth>{t('admin.newResource')}</Button></Stack></CardContent></Card></Grid></Grid></>; }
