import { useState } from 'react';
import { Button, Card, CardContent, Chip, Grid, Stack, TextField, Typography } from '@mui/material';
import AddRoundedIcon from '@mui/icons-material/AddRounded';
import DeleteOutlineRoundedIcon from '@mui/icons-material/DeleteOutlineRounded';
import { useLanguage, useTranslation } from '../../contexts/LanguageContext';
import { categories as initialCategories } from '../../data/contentData';

export default function CategoriesPage() { const { t } = useTranslation(); const { language } = useLanguage(); const [items, setItems] = useState(initialCategories); const [name, setName] = useState(''); const [nameTa, setNameTa] = useState(''); const add = () => { if (!name || !nameTa) return; setItems((current) => [...current, { id: name.toLowerCase().replace(/\s+/g, '-'), name_en: name, name_ta: nameTa, icon: '🌱', color: '#e7f3df' }]); setName(''); setNameTa(''); }; return <><Typography className="eyebrow">ADMIN / TAXONOMY</Typography><Typography variant="h3" sx={{ mt: 1 }}>{t('admin.categories')}</Typography><Typography color="text.secondary" sx={{ mt: 1, mb: 4 }}>{t('admin.categoriesText')}</Typography><Grid container spacing={2.5}><Grid size={{ xs: 12, md: 5 }}><Card><CardContent sx={{ p: 3 }}><Typography variant="h6">{t('admin.addCategory')}</Typography><Stack gap={2} sx={{ mt: 2 }}><TextField label="English name" value={name} onChange={(event) => setName(event.target.value)} /><TextField label="Tamil name" value={nameTa} onChange={(event) => setNameTa(event.target.value)} /><Button onClick={add} variant="contained" startIcon={<AddRoundedIcon />}>Add category</Button></Stack></CardContent></Card></Grid><Grid size={{ xs: 12, md: 7 }}><Card><CardContent sx={{ p: 3 }}><Stack gap={1}>{items.map((item) => <Stack key={item.id} direction="row" alignItems="center" justifyContent="space-between" sx={{ p: 1.5, border: '1px solid', borderColor: 'divider', borderRadius: 2 }}><Stack direction="row" gap={1.5} alignItems="center"><Typography fontSize={24}>{item.icon}</Typography><BoxText item={item} language={language} /></Stack><Chip icon={<DeleteOutlineRoundedIcon />} label="Remove" onClick={() => setItems((current) => current.filter((entry) => entry.id !== item.id))} variant="outlined" /></Stack>)}</Stack></CardContent></Card></Grid></Grid></>; }
function BoxText({ item, language }) { return <Stack><Typography fontWeight={700}>{item[`name_${language}`]}</Typography><Typography variant="caption" color="text.secondary">{item.name_en} · {item.name_ta}</Typography></Stack>; }
